esphome:
  name: ${name}
  comment: '${device_description}'
  name_add_mac_suffix: false

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "DfFA+xoc8v6zNL/36RpxYA2Ho5Jr7gKF9gMK/b1Cjzo="

ota:
  password: "562a2f9951b210dea1cd8ce7b014c7ab"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Meter Fallback Hotspot"
    password: "84H23SkgQq12"

captive_portal:

substitutions:
  device_name: "Water_Meter"
  name: "water-meter"
  friendly_name: "Water Meter"
  device_description: "Measure the household water consumption"
  relay_restore_mode: RESTORE_DEFAULT_ON

# Send WiFi signal strength & uptime to HA
sensor:
  - platform: wifi_signal
    name: $friendly_name WiFi Strength
    update_interval: 60s

  - platform: pulse_meter
    name: "Water Flow Meter"
    id: "water_flow_meter"
    pin:
      number: 12
      inverted: true
      mode:
        input: true
        pullup: true
    internal_filter_mode: PULSE
    unit_of_measurement: "L"
    icon: "mdi:pump"
    internal_filter: 100ms
    timeout: 1min
    filters:
      - multiply: .1666666666666667
    total:
      name: 'Water Meter Total'
      id: water_meter_total
      unit_of_measurement: "L"
      state_class: "total_increasing"
      icon: "mdi:water"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
      disabled_by_default: false
    ssid:
      name: $friendly_name Connected SSID
    mac_address:
      name: $friendly_name MAC WiFi Address

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

time:
    platform: sntp

mdns:
  disabled: false

web_server:
  port: 80