  #  Enable time component to reset energy at midnight
time:
  #  Alternative sync option to sntp, using HA instances time
#    platform: homeassistant

  # Set sync to SNTP method
    platform: sntp
    id: sntp_time
  # Define the timezone of the device
    timezone: "Australia/Sydney"
  # Change sync interval from default 5min
    update_interval: 360min
  # Set specific sntp servers to use
    servers: 
      - 2.au.pool.ntp.org
      - 1.au.pool.ntp.org
      - 0.au.pool.ntp.org
  # Publish the time the device was last restarted
    on_time_sync:
      then:
        # Update last restart time, but only once.
        - if:
            condition:
              lambda: 'return id(device_last_restart).state == "";'
            then:
              - text_sensor.template.publish:
                  id: device_last_restart
                  state: !lambda 'return id(sntp_time).now().strftime("%a %d %b %Y - %H:%M:%S");'