button:
  #  Restart the ESP Device
  - platform: restart
    name: 'Restart Device'
    entity_category: diagnostic

  #  Reset the ESP Device
  - platform: factory_reset
    name: Reset with Default Settings

#  - platform: template
#    name: 'Reset - WiFi'
#    on_press:
#      then:
#        - lambda: |-
#            WiFi.disconnect();
#            WiFi.begin();
