sensor:
  #  WiFi signal strength
  - platform: wifi_signal
    name: "WiFi Strength"
    update_interval: 120s
    entity_category: diagnostic
    internal: True

  #  Sensor uptime in seconds
  - platform: uptime
    name: "Uptime Seconds"
    id: uptime_seconds
    update_interval: 120s
    entity_category: diagnostic
    internal: True
