esphome:
  name: water-meter

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ADD-YOUR-OWN-HA-DEVICE-KEY-HERE"

ota:
  password: "ADD-YOUR-OWN-OTA-DEVICE-PWD-HERE"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Update the domain suffix to your home network domain name
  domain: .iot.home.lan                         # Update to your own home DNS domain
 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water-Meter Fallback Hotspot"
    password: "ADD-YOUR-OWN-WiFi-FALLBACK-PWD-HERE"

captive_portal:


substitutions:
  device_name: "Water_Meter"
  name: "water-meter"
  friendly_name: "Water Meter"
  device_description: "Measure the household water consumption"
  relay_restore_mode: RESTORE_DEFAULT_ON

# This is for saving the total_water_used_sensor every so often, incase of a power cycle
globals:
  - id: saved_usage_count
    type: int
    restore_value: yes
  - id: save_usage_frequency
    type: int    
    initial_value: '1'

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $friendly_name IP Address
      disabled_by_default: false
    ssid:
      name: $friendly_name Connected SSID
    mac_address:
      name: $friendly_name MAC WiFi Address



binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Australia/Sydney

mdns:
  disabled: false

web_server:
  port: 80


sensor:

# Send WiFi signal strength & uptime to HA
  - platform: wifi_signal
    name: $friendly_name WiFi Strength
    update_interval: 60s

  - platform: pulse_meter
    name: "Water Flow Rate"
    id: "water_flow_rate"
    pin:
      number: 5
      inverted: true
      mode:
        input: true
        pullup: true
    internal_filter_mode: PULSE
    unit_of_measurement: "L/min"
    icon: "mdi:pump"
    internal_filter: 100ms
    timeout: 1min
    total:
      name: 'Water Consumption'
      id: water_consumption
      accuracy_decimals: 2
      unit_of_measurement: "L"
      state_class: "total_increasing"
      device_class: water
      icon: "mdi:water"
      filters:
      - multiply: 0.5